### ISSUE TITLE
Fehlermeldung seit ein paar Tagen

### ISSUE THREAD

**Issue by ragalthar** [iamrbn/tagesschau-widget#1]
![image](https://user-images.githubusercontent.com/82751561/234951532-7c093e66-51f4-45ce-b68c-826331710227.jpeg)

Diese Fehlermeldung sehe ich seit einigen Tagen.

**Comment by iamrbn** [comment]
@ragalthar bugfix kommt heute oder morgen :) 

_Edit:_ Grund für den Fehler war, dass der path für teaserImages in der JSON geändert wurde.

**Comment by iamrbn** [comment]
Uploaded version 1.3 with bugfix and script improvements.
