### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by ragalthar** [iamrbn/tagesschau-widget#3]
Version 1.3 läuft, hat aber einen Rechtschreibfehler 
![image](https://github.com/iamrbn/tagesschau-widget/assets/82751561/dcfb7d47-94f1-458d-b973-be567c40898f)
[Edit] Der Rechtschreibfehler ist in Zeile 661

**Comment by ragalthar** [comment]
Läuft wohl doch nicht

![image](https://github.com/iamrbn/tagesschau-widget/assets/82751561/aaa228b9-e330-4acf-81e7-c7f4232ab386)

**Comment by iamrbn** [comment]
> Version 1.3 läuft, hat aber einen Rechtschreibfehler
> ![image](https://user-images.githubusercontent.com/82751561/238894603-dcfb7d47-94f1-458d-b973-be567c40898f.jpeg)
> [Edit] Der Rechtschreibfehler ist in Zeile 661

Schreibfehler wurde im neusten update beseitigt.


> Läuft wohl doch nicht
> 
> ![image](https://user-images.githubusercontent.com/82751561/238895449-aaa228b9-e330-4acf-81e7-c7f4232ab386.jpeg)

Das Widget benötigt ein Widget Parameter.
Siehe [README > Widget Parameter > Ressort](https://github.com/iamrbn/tagesschau-widget#ressort)

**Comment by iamrbn** [comment]
Mit Update 1.3.1
