### ISSUE TITLE
Error bei API abfrage

### ISSUE THREAD

**Issue by iamrbn** [iamrbn/tagesschau-widget#4]
widget zeigt ein fehler an, dass die daten aus der API nicht das korrekte format haben.

**Comment by ragalthar** [comment]
![image](https://github.com/user-attachments/assets/0f323d71-51d6-4e32-939e-22ab3330c35b)
Das ist die Fehlermeldung, die man im Widget sieht.

Und hier die Fehlermeldung, wenn man das Script in Scriptable direkt startet:
![image](https://github.com/user-attachments/assets/575050d1-0436-4837-be3c-c566514a7ed2)
... und ja, ich habe eine Internet-Verbindung aktiv, wie sonst könnte ich das hier schreiben?

**Comment by iamrbn** [comment]
sollte mit dem update auf 1.4 behoben sein.
