### ISSUE TITLE
Fehler bei NoThumbnail (Widget Small)

### ISSUE THREAD

**Issue by drkWin78** [iamrbn/tagesschau-widget#5]
Ich bin großer Fan vom tagesschau Widget 👍🏻
Wie kann ich denn die Fehlermeldung umgehen (No Thumbnail) beim kleinen Widget?! Hab schon versucht das Hintergrundbild anzupassen: leider ohne Erfolg 🫣😃

**Comment by iamrbn** [comment]
sollte mit dem update auf 1.4 behoben sein.
